#!/bin/sh

set -e

for f in "$srcdir"/gm-*; do
	name=serialized."$(basename "$f")"
	./gmparser < "$f" > "$name"
	diff -u "$f" "$name"
done

for f in "$srcdir"/gmi-*; do
	name=serialized."$(basename "$f")"
	./gmiparser < "$f" > "$name"
	diff -u "$f" "$name"
done

set +e

out=$(mktemp -p .)
printf '\357\273\277# hello' | ./gmiparser >"$out"
echo "# hello" | diff -u "$out" -
ret=$?
rm $out
exit $ret
