#!/bin/sh

set -e

for f in "$srcdir"/mc.test.*; do
	name=serialized."$(basename "$f")"
	./mailcap < "$f" > "$name"

	exp="$(basename "$f")"
	exp="$srcdir/mc.exp.${exp##mc.test.}"

	diff -u "$exp" "$name"
	rm "$name"
done
