telescope_ubuntu_task:
  container:
    image: ubuntu:latest
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
  test_script: make check

telescope_alpine_linux_task:
  container:
    image: alpine:latest
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
  test_script: make check

telescope_freebsd_task:
  freebsd_instance:
    image_family: freebsd-14-2
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
  test_script: make check

telescope_macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
  test_script: make check
