matrix:
  TELESCOPE_BASE_IMAGE:
    - ghcr.io/telescope-browser/tbi-alpine:latest
    - ghcr.io/telescope-browser/tbi-debian:latest

when:
  - event: [tag, push, pull_request]

steps:
  - name: build
    image: ${TELESCOPE_BASE_IMAGE}
    commands:
      - ./.github/ci/before-install.sh
      - ./autogen.sh
      - ./configure
      - make
      - make check
